# Generated by DataMan Engine
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("status_code", models.IntegerField()),
                ("duration_ms", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "dataman_apilog",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=8, unique=True)),
                ("hashed_secret", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "dataman_apitoken",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=60)),
                (
                    "actor",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(db_index=True, default="INFO", max_length=20),
                ),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "dataman_auditlog",
                "ordering": ["-timestamp"],
            },
        ),
    ]
