import secrets
from pathlib import Path

import click
import inflection
from django.core.management import call_command

from dataman import django_setup


def _ensure_initialized():
    """Helper to ensure the current directory is a DataMan project."""
    if not Path(".env").exists() or not Path("tables").is_dir():
        click.echo(
            click.style(
                "Error: Not a DataMan project. Run 'dataman init' first.", fg="red"
            )
        )
        raise click.Abort()


@click.group()
def cli():
    """Data MiddleMan (DataMan) CLI"""
    pass


@cli.command()
def init():
    """Initialize a new DataMan project in the current directory."""
    cwd = Path.cwd()
    env_path = cwd / ".env"
    tables_dir = cwd / "tables"

    if env_path.exists() or tables_dir.exists():
        click.echo(
            click.style("Project already initialized in this directory.", fg="yellow")
        )
        return

    # Create .env
    secret_key = secrets.token_urlsafe(50)
    with open(env_path, "w") as f:
        f.write(f"DATAMAN_SECRET_KEY='{secret_key}'\n")
        f.write("DEBUG=True\n")
        f.write("DATABASE_URL=sqlite:///db.sqlite3\n")
        f.write("ALLOWED_HOSTS=127.0.0.1,localhost\n")
    click.echo(click.style("Created .env file.", fg="green"))

    # Create tables directory
    tables_dir.mkdir()
    (tables_dir / "__init__.py").touch()
    click.echo(click.style("Created tables/ directory.", fg="green"))

    # Generate initial migrations package
    migrations_dir = tables_dir / "migrations"
    migrations_dir.mkdir()
    (migrations_dir / "__init__.py").touch()

    click.echo(
        click.style("DataMan project initialized successfully!", fg="green", bold=True)
    )


@cli.group()
def create():
    """Create resources like tables."""
    pass


@create.command(name="table")
@click.argument("name")
@click.option(
    "--operations",
    "-o",
    default="crud",
    help="Allowed operations: c (create), r (read), u (update), d (delete).",
)
def create_table(name, operations):
    """Scaffold a new database table and API endpoint."""
    _ensure_initialized()

    # Sanitize inputs
    if "/" in name or "\\" in name or "." in name:
        click.echo(click.style("Invalid table name.", fg="red"))
        raise click.Abort()

    table_name = inflection.camelize(name)

    if not table_name.isidentifier():
        click.echo(
            click.style(
                f"Invalid table name: '{table_name}' is not a valid Python identifier.",
                fg="red",
            )
        )
        raise click.Abort()

    table_dir = Path.cwd() / "tables" / table_name

    if table_dir.exists():
        click.echo(click.style(f"Table '{table_name}' already exists.", fg="yellow"))
        raise click.Abort()

    table_dir.mkdir(parents=True)
    (table_dir / "__init__.py").touch()

    ops_map = {"c": "C", "r": "R", "u": "U", "d": "D"}
    ops_list = [ops_map[char] for char in operations.lower() if char in ops_map]

    # Write config.py
    with open(table_dir / "config.py", "w") as f:
        f.write(f"ALLOWED_OPERATIONS = {ops_list}\n")
        f.write("REQUIRE_AUTH = True\n")
        scopes = [f"{table_name.lower()}:read", f"{table_name.lower()}:write"]
        f.write(f"TABLE_SCOPES = {scopes}\n")
        f.write("THROTTLE_RATES = {'anon': '100/day', 'user': '1000/day'}\n")
        f.write("WEBHOOK_URLS = []\n")
        f.write("DEPTH = 0  # Set to 1 or higher to automatically serialize nested relationships\n")

    # Write models.py
    with open(table_dir / "models.py", "w") as f:
        f.write("from django.db import models\n\n")
        f.write(f"class {table_name}(models.Model):\n")
        f.write("    # Add your fields here\n")
        f.write("    created_at = models.DateTimeField(auto_now_add=True)\n")
        f.write("    updated_at = models.DateTimeField(auto_now=True)\n\n")
        f.write("    class Meta:\n")
        f.write("        app_label = 'dataman'\n")
        f.write(f"        db_table = '{table_name.lower()}'\n")

    # Write validation.py
    with open(table_dir / "validation.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# Define custom validation logic or Pydantic Schemas here.\n"
            "# \n"
            "# Example:\n"
            "# from pydantic import BaseModel, Field\n"
            "# \n"
            "# class Schema(BaseModel):\n"
            "#     name: str = Field(..., min_length=2, max_length=255)\n"
        )

    # Write service.py
    with open(table_dir / "service.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# DataMan automatically handles standard CRUD.\n"
            "# You can override insert/fetch behavior here if needed.\n"
        )

    # Write analytics.py
    with open(table_dir / "analytics.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# Define custom tracking or metrics hooks for this table here.\n"
        )

    click.echo(
        click.style(
            f"Successfully created table structure for {table_name}!", fg="green"
        )
    )


@cli.command()
def makemigration():
    """Create new migrations based on the models you have defined."""
    _ensure_initialized()
    django_setup.setup()
    try:
        call_command("makemigrations", "dataman")
        click.echo(click.style("Migrations created successfully!", fg="green"))
    except SystemExit as e:
        raise click.Abort() from e


@cli.command()
def migrate():
    """Apply migrations to the database."""
    _ensure_initialized()
    django_setup.setup()
    try:
        call_command("migrate")
        click.echo(click.style("Database migrated successfully!", fg="green"))
    except SystemExit as e:
        raise click.Abort() from e


@cli.group()
def server():
    """Manage the DataMan server."""
    pass


@server.command()
def start():
    """Start the DataMan API server."""
    _ensure_initialized()
    django_setup.setup()
    try:
        click.echo(
            click.style(
                "Starting DataMan server at http://127.0.0.1:8000/",
                fg="green",
                bold=True,
            )
        )
        call_command("runserver", "127.0.0.1:8000", use_reloader=False)
    except SystemExit as e:
        raise click.Abort() from e


@cli.group()
def users():
    """Manage DataMan users and tokens."""
    pass


@users.command(name="create-admin")
def create_admin():
    """Create a superuser for the admin panel."""
    _ensure_initialized()
    django_setup.setup()
    try:
        call_command("createsuperuser")
    except SystemExit as e:
        raise click.Abort() from e


@users.command(name="create-token")
@click.argument("name")
@click.option(
    "--scopes",
    default="*",
    help=(
        "Comma separated list of scopes (e.g. 'customer:read,invoice:write'). "
        "Use '*' for all scopes."
    ),
)
def create_token(name, scopes):
    """Generate a programmatic API token."""
    _ensure_initialized()
    django_setup.setup()

    import hashlib
    import json
    import secrets

    from dataman.core.models import APIToken

    scope_list = [s.strip() for s in scopes.split(",")]

    prefix = secrets.token_hex(4)
    secret = secrets.token_hex(16)
    hashed_secret = hashlib.sha256(secret.encode()).hexdigest()

    APIToken.objects.create(
        name=name, scopes=scope_list, prefix=prefix, hashed_secret=hashed_secret
    )
    click.echo(f"Created new token: {name}")
    click.echo(f"Scopes: {json.dumps(scope_list)}")
    click.echo(click.style(f"Token Key: {prefix}_{secret}", fg="green", bold=True))
    click.echo(
        click.style(
            "Please save this token key securely. It will not be shown again.",
            fg="yellow",
        )
    )


if __name__ == "__main__":
    cli()
