from pathlib import Path

import click


@click.group()
def cli():
    """DataMan: Headless Data Layer API Generator."""
    pass


@cli.command()
def init():
    """Initialize a new DataMan project in the current directory."""
    cwd = Path.cwd()

    # Create .env.example file
    env_path = cwd / ".env.example"
    if not env_path.exists():
        with open(env_path, "w") as f:
            f.write("DEBUG=True\n")
            f.write("DATAMAN_SECRET_KEY=insecure-default-key-please-change\n")
            f.write("DATABASE_URL=sqlite:///db.sqlite3\n")
        click.echo(click.style("Created .env.example file.", fg="green"))
    else:
        click.echo(
            click.style(".env.example file already exists, skipping.", fg="yellow")
        )

    # Create tables directory
    tables_dir = cwd / "tables"
    if not tables_dir.exists():
        tables_dir.mkdir()
        click.echo(click.style("Created tables/ directory.", fg="green"))

        # Create an __init__.py inside it to make it a package
        init_file = tables_dir / "__init__.py"
        init_file.touch()
    else:
        click.echo(
            click.style("tables/ directory already exists, skipping.", fg="yellow")
        )

    click.echo(
        click.style("DataMan project initialized successfully!", fg="green", bold=True)
    )


@cli.group()
def create():
    """Create resources."""
    pass


@create.command(name="table")
@click.argument("table_name")
@click.option(
    "--operations",
    "-o",
    default="crud",
    help="Allowed operations (c=create, r=read, u=update, d=delete)",
)
def create_table(table_name: str, operations: str):
    """Scaffold a new table structure."""
    cwd = Path.cwd()
    tables_dir = cwd / "tables"

    if not tables_dir.exists():
        click.echo(
            click.style(
                "Error: tables/ directory not found. Did you run 'dataman init'?",
                fg="red",
            )
        )
        raise click.Abort()

    # Create table directory
    table_dir = tables_dir / table_name
    if table_dir.exists():
        click.echo(
            click.style(
                f"Error: Table directory {table_name} already exists.", fg="red"
            )
        )
        raise click.Abort()

    table_dir.mkdir()
    (table_dir / "__init__.py").touch()

    # Parse operations
    ops_map = {"c": "C", "r": "R", "u": "U", "d": "D"}
    ops_list = [ops_map[char] for char in operations.lower() if char in ops_map]

    # Write config.py
    with open(table_dir / "config.py", "w") as f:
        f.write(
            f"# Auto-generated by DataMan\n"
            f"# Allowed operations for this endpoint\n"
            f"ALLOWED_OPERATIONS = {ops_list}\n"
        )

    # Write model.py
    db_table_name = "".join(
        ["_" + c.lower() if c.isupper() else c for c in table_name]
    ).lstrip("_")
    with open(table_dir / "model.py", "w") as f:
        f.write(
            f"# Auto-generated by DataMan\n"
            f"from django.db import models\n\n\n"
            f"class {table_name}(models.Model):\n"
            f"    # Define your fields here, for example:\n"
            f"    # name = models.CharField(max_length=255)\n\n"
            f"    class Meta:\n"
            f'        db_table = "{db_table_name}"\n'
        )

    # Write validation.py
    with open(table_dir / "validation.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# DataMan automatically generates DRF Serializers.\n"
            "# You can define custom validation logic here if needed.\n"
        )

    # Write service.py
    with open(table_dir / "service.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# DataMan automatically handles standard CRUD.\n"
            "# You can override insert/fetch behavior here if needed.\n"
        )

    # Write analytics.py
    with open(table_dir / "analytics.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# Define custom tracking or metrics hooks for this table here.\n"
        )

    click.echo(
        click.style(
            f"Successfully created table structure for {table_name}!",
            fg="green",
        )
    )


if __name__ == "__main__":
    cli()
