import re
from pathlib import Path

import click
import inflection
from django.core.management import call_command

from dataman import django_setup


@click.group()
def cli():
    """DataMan: Headless Data Layer API Generator."""
    pass


@cli.command()
def init():
    """Initialize a new DataMan project in the current directory."""
    cwd = Path.cwd()

    # Create .env file
    env_path = cwd / ".env"
    if not env_path.exists():
        import secrets

        secret_key = secrets.token_urlsafe(50)
        with open(env_path, "w") as f:
            f.write("DEBUG=False\n")
            f.write(f"DATAMAN_SECRET_KEY={secret_key}\n")
            f.write("DATABASE_URL=sqlite:///db.sqlite3\n")
            f.write("ALLOWED_HOSTS=\n")
        click.echo(click.style("Created .env file.", fg="green"))
    else:
        click.echo(click.style(".env file already exists, skipping.", fg="yellow"))

    # Create tables directory
    tables_dir = cwd / "tables"
    if not tables_dir.exists():
        tables_dir.mkdir()
        click.echo(click.style("Created tables/ directory.", fg="green"))

        # Create an __init__.py inside it to make it a package
        init_file = tables_dir / "__init__.py"
        init_file.touch()
    else:
        click.echo(
            click.style("tables/ directory already exists, skipping.", fg="yellow")
        )

    click.echo(
        click.style("DataMan project initialized successfully!", fg="green", bold=True)
    )


@cli.group()
def create():
    """Create resources."""
    pass


@create.command(name="table")
@click.argument("table_name")
@click.option(
    "--operations",
    "-o",
    default="crud",
    help="Allowed operations (c=create, r=read, u=update, d=delete)",
)
def create_table(table_name: str, operations: str):
    """Scaffold a new table structure."""
    if not re.match(r"^[a-zA-Z0-9_]+$", table_name):
        click.echo(
            click.style(
                "Error: Invalid table name. "
                "Use only alphanumeric characters and underscores.",
                fg="red",
            )
        )
        raise click.Abort()

    table_name = inflection.camelize(table_name)

    cwd = Path.cwd()
    tables_dir = cwd / "tables"

    if not tables_dir.exists():
        click.echo(
            click.style(
                "Error: tables/ directory not found. Did you run 'dataman init'?",
                fg="red",
            )
        )
        raise click.Abort()

    # Create table directory
    table_dir = tables_dir / table_name
    if table_dir.exists():
        click.echo(
            click.style(
                f"Error: Table directory {table_name} already exists.", fg="red"
            )
        )
        raise click.Abort()

    table_dir.mkdir()
    (table_dir / "__init__.py").touch()

    # Parse operations
    ops_map = {"c": "C", "r": "R", "u": "U", "d": "D"}
    ops_list = [ops_map[char] for char in operations.lower() if char in ops_map]

    # Write config.py
    with open(table_dir / "config.py", "w") as f:
        f.write(
            f"# Auto-generated by DataMan\n\n"
            f"# Allowed operations for this endpoint\n"
            f"ALLOWED_OPERATIONS = {ops_list}\n\n"
            f"# Set to True to require token authentication for this endpoint\n"
            f"REQUIRE_AUTH = True\n\n"
            f"# API Features & Capabilities\n"
            f"PAGE_SIZE = None\n"
            f"FILTER_FIELDS = []\n"
            f"SEARCH_FIELDS = []\n"
            f"ORDERING_FIELDS = []\n"
            f"WEBHOOK_URL = None\n"
            f"RATE_LIMIT = None  # e.g., '100/day', '10/minute'\n"
        )

    # Write model.py
    db_table_name = "".join(
        ["_" + c.lower() if c.isupper() else c for c in table_name]
    ).lstrip("_")
    with open(table_dir / "model.py", "w") as f:
        f.write(
            f"# Auto-generated by DataMan\n"
            f"from django.db import models\n\n\n"
            f"class {table_name}(models.Model):\n"
            f"    # Define your fields here, for example:\n"
            f"    # name = models.CharField(max_length=255)\n\n"
            f"    class Meta:\n"
            f'        app_label = "dataman"\n'
            f'        db_table = "{db_table_name}"\n'
        )

    # Write validation.py
    with open(table_dir / "validation.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# Define custom validation logic or Pydantic Schemas here.\n"
            "# \n"
            "# Example:\n"
            "# from pydantic import BaseModel, Field\n"
            "# \n"
            "# class Schema(BaseModel):\n"
            "#     name: str = Field(..., min_length=2, max_length=255)\n"
        )

    # Write service.py
    with open(table_dir / "service.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# DataMan automatically handles standard CRUD.\n"
            "# You can override insert/fetch behavior here if needed.\n"
        )

    # Write analytics.py
    with open(table_dir / "analytics.py", "w") as f:
        f.write(
            "# Auto-generated by DataMan\n"
            "# Define custom tracking or metrics hooks for this table here.\n"
        )

    click.echo(
        click.style(
            f"Successfully created table structure for {table_name}!",
            fg="green",
        )
    )


@cli.command()
def makemigration():
    """Create new migrations based on the models you have defined."""
    django_setup.setup()
    try:
        call_command("makemigrations", "dataman")
        click.echo(click.style("Migrations created successfully!", fg="green"))
    except SystemExit as e:
        # Django's call_command might call sys.exit if there's an error
        raise click.Abort() from e


@cli.command()
def migrate():
    """Apply migrations to the database."""
    django_setup.setup()
    try:
        call_command("migrate")
        click.echo(click.style("Database migrated successfully!", fg="green"))
    except SystemExit as e:
        raise click.Abort() from e


@cli.group()
def server():
    """Manage the DataMan server."""
    pass


@server.command()
def start():
    """Start the DataMan API server."""
    django_setup.setup()
    try:
        click.echo(
            click.style(
                "Starting DataMan server at http://127.0.0.1:8000/",
                fg="green",
                bold=True,
            )
        )
        call_command("runserver", "127.0.0.1:8000", use_reloader=False)
    except SystemExit as e:
        raise click.Abort() from e


@cli.group()
def users():
    """Manage DataMan users and tokens."""
    pass


@users.command(name="create-admin")
def create_admin():
    """Create a superuser for the admin panel."""
    django_setup.setup()
    try:
        call_command("createsuperuser")
    except SystemExit as e:
        raise click.Abort() from e


@users.command(name="create-token")
@click.argument("name")
@click.option(
    "--scopes",
    default="*",
    help=(
        "Comma separated list of scopes (e.g. 'customer:read,invoice:write'). "
        "Default is '*'."
    ),
)
def create_token(name, scopes):
    """Generate an API Service Token with specific scopes."""
    django_setup.setup()
    import hashlib
    import json
    import secrets

    from dataman.core.models import APIToken

    scope_list = [s.strip() for s in scopes.split(",")]

    prefix = secrets.token_hex(4)
    secret = secrets.token_hex(16)
    hashed_secret = hashlib.sha256(secret.encode()).hexdigest()

    APIToken.objects.create(
        name=name, scopes=scope_list, prefix=prefix, hashed_secret=hashed_secret
    )
    click.echo(f"Created new token: {name}")
    click.echo(f"Scopes: {json.dumps(scope_list)}")
    click.echo(click.style(f"Token Key: {prefix}_{secret}", fg="green", bold=True))
    click.echo(
        click.style(
            "Please save this token key securely. It will not be shown again.",
            fg="yellow",
        )
    )


if __name__ == "__main__":
    cli()
